Metrics/LineLength:
  Max: 140
Metrics/AbcSize:
  Max: 18
Style/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "*.gemspec"
