sudo: required
language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.15.1

script:
  - bundle install
  - bundle exec rspec

notifications:
  slack:
    rooms: creative-group-team:HbG6Us2kmwJUpSchT64NmZ9G
    on_success: always
